# 第一章 预备知识

## 1.1 Python基础

### 1.1.1 推导式

In [82]:
# exp_1
str_list = ["green", "black", "white", "red", "bule"]
str_dict = {item: len(item) for item in str_list}
str_dict

{'green': 5, 'black': 5, 'white': 5, 'red': 3, 'bule': 4}

In [83]:
# exp_2
import random

L1 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
L2 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
L3 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
# L_min = [[min(m1, m2, m3) for m1 in n1 for m2 in n2 for m3 in n3] for n1 in L1 for n2 in L2 for n3 in L3]
L_min = [[min(m1, m2, m3) for m1,m2,m3 in zip(n1,n2,n3)] for n1,n2,n3 in zip(L1,L2,L3)]
L_min


[[17,
  58,
  38,
  14,
  30,
  13,
  10,
  21,
  19,
  12,
  15,
  19,
  18,
  17,
  35,
  19,
  10,
  24,
  18,
  15],
 [38, 10, 86, 5, 9, 23, 6, 38, 32, 31, 12, 2, 2, 53, 8, 17, 21, 12, 14, 1],
 [63,
  20,
  44,
  46,
  10,
  16,
  28,
  59,
  59,
  62,
  24,
  2,
  44,
  79,
  15,
  81,
  27,
  17,
  11,
  10],
 [2, 22, 26, 49, 66, 65, 0, 59, 24, 22, 25, 28, 26, 22, 57, 3, 3, 60, 10, 19],
 [8, 12, 0, 10, 0, 26, 46, 50, 21, 7, 45, 15, 8, 19, 43, 19, 27, 24, 32, 47],
 [8, 19, 20, 51, 22, 38, 6, 10, 10, 36, 33, 6, 32, 42, 7, 15, 36, 44, 38, 36],
 [2, 1, 10, 7, 4, 6, 24, 71, 64, 18, 12, 44, 68, 63, 22, 26, 37, 11, 29, 57],
 [64, 1, 4, 0, 75, 60, 36, 2, 74, 1, 29, 2, 48, 2, 3, 9, 0, 33, 72, 61],
 [29, 1, 13, 20, 41, 41, 13, 4, 4, 35, 10, 66, 47, 8, 3, 31, 17, 11, 29, 3],
 [19, 3, 8, 71, 13, 21, 2, 41, 15, 1, 22, 13, 65, 12, 1, 58, 48, 28, 39, 0],
 [8, 66, 15, 16, 27, 48, 2, 12, 18, 0, 30, 9, 11, 9, 63, 41, 71, 12, 31, 2],
 [1, 3, 1, 41, 15, 27, 24, 3, 1, 7, 10, 37, 67, 37, 5, 2, 3, 28, 

### 1.1.2 匿名函数

In [84]:
my_list = [[1, 2], [3, 4, 5], [6], [7, 8], [9]]
list(filter(lambda x:any(True if i%3==0 else False for i in x) , my_list))


[[3, 4, 5], [6], [9]]

### 1.1.3 打包函数

In [85]:
def diy_enumerate(l_num:list):
    return list(zip(range(len(l_num)),l_num))
list_1=['A','B','C','D']
diy_enumerate(list_1)
    
    

[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')]

## 1.2 Numpy 函数

In [86]:
import numpy as np
array_1=np.arange(0,10).reshape(10,1)
na_l=np.repeat(array_1,repeats=10,axis=1)
na_l.T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [87]:
target=np.arange(24).reshape((4,2,3))
print(target)
target[:,np.newaxis,np.newaxis].shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


(4, 1, 1, 2, 3)

In [88]:
import numpy as np
da_11=np.random.randint(1,100,size=(10,10))
print(da_11)
da_softmax=np.exp(da_11)/np.sum(np.exp(da_11),axis=1)
print(da_softmax)

[[24 54 52 47 21 54 30 68 36 40]
 [10 74 42 24  4 47 91 51  4 32]
 [10 11 28 46 72 40 62 86 98 45]
 [35 35 89 34  6 37  1 76 35 70]
 [54 81 63  9 62  2 82 36 92 41]
 [37 49 26 68 36 31 30 34 19 18]
 [94 85  3 70 13 45 67 92 86 40]
 [40 76 23 31 18 71 72 19 93 44]
 [84 50 42 94 47 22 74 90 97 92]
 [74 29 82 59  1 87 64 17 37 95]]
[[7.78111842e-20 8.53304727e-17 1.05305527e-20 5.74950924e-19
  1.46239541e-31 8.31528714e-07 1.41206123e-28 1.38879433e-11
  3.04635994e-27 1.29914267e-24]
 [6.47022343e-26 4.13993755e-08 4.78086351e-25 5.90007717e-29
  6.05422592e-39 7.58256039e-10 4.38345876e-02 5.74952202e-19
  3.85796066e-41 4.35813815e-28]
 [6.47022343e-26 1.80485131e-35 3.97542531e-31 2.11512624e-19
  2.06102563e-09 6.91440007e-13 1.11500535e-14 9.11881927e-04
  2.57062717e+00 1.92809868e-22]
 [4.65887787e-15 4.78089269e-25 1.23409046e-04 1.29957848e-24
  4.47350149e-38 3.44247709e-14 3.59181164e-41 4.13993754e-08
  1.12069319e-27 1.38832552e-11]
 [8.31527242e-07 4.53999279e-05 6.3050780

In [89]:
da_12=np.random.randint(0,100,size=(4,5))
np.where(np.amax(da_12,axis=1)[:,None]==da_12,1,0)

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])

In [90]:
da_array=np.random.rand(1000,3)
res=da_array[(da_array.sum(axis=1)<=1.5)|((da_array[:,0]>0.5) & (da_array[:,2]>0.5))]
(res.sum(axis=1)<=1.5)|(res[:,[0,2]]>0.5).all(axis=1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [91]:
da_r=np.round(da_array)
((da_r==0)|(da_r==1)).all()
da_r[da_r.sum(axis=1)<=1]
da_r[da_r.sum(axis=1)!=3]
da_r[(da_r.sum(axis=1)!=0)&(da_r.sum(axis=1)!=3)]

array([[0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [92]:
da_14=np.random.randint(0,10,size=(4,3))
da_clip_1=np.clip(da_14,3.5,6.5)
da_clip_t=np.where(da_14<3.5,3.5,da_14)
da_clip_2=np.where(da_clip_t>6.5,6.5,da_clip_t)
print(da_clip_1)
print(da_clip_2)
(da_clip_1==da_clip_2).all()

[[6.5 3.5 3.5]
 [6.5 6.5 6.5]
 [3.5 3.5 3.5]
 [6.5 6.5 3.5]]
[[6.5 3.5 3.5]
 [6.5 6.5 6.5]
 [3.5 3.5 3.5]
 [6.5 6.5 3.5]]


True

In [93]:
np.random.seed(0)
da_15=np.random.randint(0,3,size=(3,3))
print(da_15)
da_15[np.nonzero(da_15)]

[[0 1 0]
 [1 1 2]
 [0 2 0]]


array([1, 1, 1, 2, 2])

## 1.3 习题

In [94]:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(3,2)
c=[[(a[i,:]*(b[:,j])).sum() for j in range(2)] for i in range(2)]
print(a@b)
print(c)

[[10 13]
 [28 40]]
[[10, 13], [28, 40]]


In [95]:
np.random.seed(0)
A=np.random.randint(10,20,(8,5))
B=(A.sum(1)[:,None].dot(A.sum(0).reshape(1,5)))/A.sum()
kar_t=((A-B)**2/B).sum()
kar_t

11.842696601945802

In [96]:
np.random.seed(0)
data_Y_M=np.random.randint(100,200,size=(20,12))
data_Y_Q=np.sum(np.split(data_Y_M,3,1),axis=0)