# 第一章 预备知识

## 1.1 Python基础

### 1.1.1 推导式

In [82]:
# exp_1
str_list = ["green", "black", "white", "red", "bule"]
str_dict = {item: len(item) for item in str_list}
str_dict

{'green': 5, 'black': 5, 'white': 5, 'red': 3, 'bule': 4}

In [83]:
# exp_2
import random

L1 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
L2 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
L3 = [[random.randint(0, 100) for m in range(20)] for n in range(30)]
# L_min = [[min(m1, m2, m3) for m1 in n1 for m2 in n2 for m3 in n3] for n1 in L1 for n2 in L2 for n3 in L3]
L_min = [[min(m1, m2, m3) for m1, m2, m3 in zip(n1, n2, n3)] for n1, n2, n3 in zip(L1, L2, L3)]
L_min


[[17,
  58,
  38,
  14,
  30,
  13,
  10,
  21,
  19,
  12,
  15,
  19,
  18,
  17,
  35,
  19,
  10,
  24,
  18,
  15],
 [38, 10, 86, 5, 9, 23, 6, 38, 32, 31, 12, 2, 2, 53, 8, 17, 21, 12, 14, 1],
 [63,
  20,
  44,
  46,
  10,
  16,
  28,
  59,
  59,
  62,
  24,
  2,
  44,
  79,
  15,
  81,
  27,
  17,
  11,
  10],
 [2, 22, 26, 49, 66, 65, 0, 59, 24, 22, 25, 28, 26, 22, 57, 3, 3, 60, 10, 19],
 [8, 12, 0, 10, 0, 26, 46, 50, 21, 7, 45, 15, 8, 19, 43, 19, 27, 24, 32, 47],
 [8, 19, 20, 51, 22, 38, 6, 10, 10, 36, 33, 6, 32, 42, 7, 15, 36, 44, 38, 36],
 [2, 1, 10, 7, 4, 6, 24, 71, 64, 18, 12, 44, 68, 63, 22, 26, 37, 11, 29, 57],
 [64, 1, 4, 0, 75, 60, 36, 2, 74, 1, 29, 2, 48, 2, 3, 9, 0, 33, 72, 61],
 [29, 1, 13, 20, 41, 41, 13, 4, 4, 35, 10, 66, 47, 8, 3, 31, 17, 11, 29, 3],
 [19, 3, 8, 71, 13, 21, 2, 41, 15, 1, 22, 13, 65, 12, 1, 58, 48, 28, 39, 0],
 [8, 66, 15, 16, 27, 48, 2, 12, 18, 0, 30, 9, 11, 9, 63, 41, 71, 12, 31, 2],
 [1, 3, 1, 41, 15, 27, 24, 3, 1, 7, 10, 37, 67, 37, 5, 2, 3, 28, 

### 1.1.2 匿名函数

In [84]:
my_list = [[1, 2], [3, 4, 5], [6], [7, 8], [9]]
list(filter(lambda x: any(True if i % 3 == 0 else False for i in x), my_list))


[[3, 4, 5], [6], [9]]

### 1.1.3 打包函数

In [85]:
def diy_enumerate(l_num: list):
    return list(zip(range(len(l_num)), l_num))


list_1 = ['A', 'B', 'C', 'D']
diy_enumerate(list_1)



[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')]

## 1.2 Numpy 函数

In [86]:
import numpy as np

array_1 = np.arange(0, 10).reshape(10, 1)
na_l = np.repeat(array_1, repeats=10, axis=1)
na_l.T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [87]:
target = np.arange(24).reshape((4, 2, 3))
print(target)
target[:, np.newaxis, np.newaxis].shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


(4, 1, 1, 2, 3)

In [88]:
import numpy as np

da_11 = np.random.randint(1, 100, size=(10, 10))
print(da_11)
da_softmax = np.exp(da_11) / np.sum(np.exp(da_11), axis=1)
print(da_softmax)

[[24 54 52 47 21 54 30 68 36 40]
 [10 74 42 24  4 47 91 51  4 32]
 [10 11 28 46 72 40 62 86 98 45]
 [35 35 89 34  6 37  1 76 35 70]
 [54 81 63  9 62  2 82 36 92 41]
 [37 49 26 68 36 31 30 34 19 18]
 [94 85  3 70 13 45 67 92 86 40]
 [40 76 23 31 18 71 72 19 93 44]
 [84 50 42 94 47 22 74 90 97 92]
 [74 29 82 59  1 87 64 17 37 95]]
[[7.78111842e-20 8.53304727e-17 1.05305527e-20 5.74950924e-19
  1.46239541e-31 8.31528714e-07 1.41206123e-28 1.38879433e-11
  3.04635994e-27 1.29914267e-24]
 [6.47022343e-26 4.13993755e-08 4.78086351e-25 5.90007717e-29
  6.05422592e-39 7.58256039e-10 4.38345876e-02 5.74952202e-19
  3.85796066e-41 4.35813815e-28]
 [6.47022343e-26 1.80485131e-35 3.97542531e-31 2.11512624e-19
  2.06102563e-09 6.91440007e-13 1.11500535e-14 9.11881927e-04
  2.57062717e+00 1.92809868e-22]
 [4.65887787e-15 4.78089269e-25 1.23409046e-04 1.29957848e-24
  4.47350149e-38 3.44247709e-14 3.59181164e-41 4.13993754e-08
  1.12069319e-27 1.38832552e-11]
 [8.31527242e-07 4.53999279e-05 6.3050780

In [89]:
da_12 = np.random.randint(0, 100, size=(4, 5))
np.where(np.amax(da_12, axis=1)[:, None] == da_12, 1, 0)

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0]])

In [90]:
da_array = np.random.rand(1000, 3)
res = da_array[(da_array.sum(axis=1) <= 1.5) | ((da_array[:, 0] > 0.5) & (da_array[:, 2] > 0.5))]
(res.sum(axis=1) <= 1.5) | (res[:, [0, 2]] > 0.5).all(axis=1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [91]:
da_r = np.round(da_array)
((da_r == 0) | (da_r == 1)).all()
da_r[da_r.sum(axis=1) <= 1]
da_r[da_r.sum(axis=1) != 3]
da_r[(da_r.sum(axis=1) != 0) & (da_r.sum(axis=1) != 3)]

array([[0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [92]:
da_14 = np.random.randint(0, 10, size=(4, 3))
da_clip_1 = np.clip(da_14, 3.5, 6.5)
da_clip_t = np.where(da_14 < 3.5, 3.5, da_14)
da_clip_2 = np.where(da_clip_t > 6.5, 6.5, da_clip_t)
print(da_clip_1)
print(da_clip_2)
(da_clip_1 == da_clip_2).all()

[[6.5 3.5 3.5]
 [6.5 6.5 6.5]
 [3.5 3.5 3.5]
 [6.5 6.5 3.5]]
[[6.5 3.5 3.5]
 [6.5 6.5 6.5]
 [3.5 3.5 3.5]
 [6.5 6.5 3.5]]


True

In [93]:
np.random.seed(0)
da_15 = np.random.randint(0, 3, size=(3, 3))
print(da_15)
da_15[np.nonzero(da_15)]

[[0 1 0]
 [1 1 2]
 [0 2 0]]


array([1, 1, 1, 2, 2])

## 1.3 习题

In [94]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)
c = [[(a[i, :] * (b[:, j])).sum() for j in range(2)] for i in range(2)]
print(a @ b)
print(c)

[[10 13]
 [28 40]]
[[10, 13], [28, 40]]


In [95]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
B = (A.sum(1)[:, None].dot(A.sum(0).reshape(1, 5))) / A.sum()
kar_t = ((A - B) ** 2 / B).sum()
kar_t

11.842696601945802

In [96]:
np.random.seed(0)
data_Y_M = np.random.randint(100, 200, size=(20, 12))
data_Y_Q = np.sum(np.split(data_Y_M, 3, 1), axis=0)

# 第二章 pandas基础

## 2.1 文件的读取和写入

In [1]:
import pandas as pd

file_path = r"C:\Users\Administrator\Desktop\python\pandas数据处理与分析\习题答案代码+数据集\数据集\ch2\my_csv.csv"
df_csv = pd.read_csv(file_path)
df_csv

col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [6]:
pd.read_table(
    r"C:\Users\Administrator\Desktop\python\pandas数据处理与分析\习题答案代码+数据集\数据集\ch2\my_table_special_sep.txt",
    sep=r"\|\|\|\|", engine='python')

col1                 col2
0   TS    This is an apple.
1   GQ      My name is Bob.
2   WT           Well done!

## 2.2 基本数据结构

In [13]:
s = pd.Series(data=[100, 'a', {'dic1': 5}], index=pd.Index(['id1', 20, 'third'], name='my_index'), name='my_name',
              dtype='object')
s.values
s.index
s.dtype
s.name
s.shape

(3,)

In [28]:
data = [[1, 'a', 1.2], [2, 'b', 2.2], [3, 'c', 3.2]]
df = pd.DataFrame(data=data, index=['row_{:d}'.format(i) for i in range(3)],
                  columns=['col_{:d}'.format(i) for i in range(3)])
df['col_0']
type(df[['col_0']])
df['col_0'].to_frame()
df.values
df.index
df.columns
df.dtypes
df.shape
df.T

row_0 row_1 row_2
col_0     1     2     3
col_1     a     b     c
col_2   1.2   2.2   3.2

In [33]:
df['col_4'] = ['apple', 'banana', 'cat']
df.drop(['col_0'], axis=1)
df.drop(['row_0'], axis=0)
df[df.columns[:-1]]

col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

## 2.3 常用基本函数

1. 数据操作：索引、分组、变形、连接
2. 数据类型：缺失、文本、分类、时序
3. 其它（可视化、优化等）

In [1]:
import pandas as pd

df = pd.read_csv("./src/learn_pandas.csv")
# 汇总函数
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   School       200 non-null    object 
 1   Grade        200 non-null    object 
 2   Name         200 non-null    object 
 3   Gender       200 non-null    object 
 4   Height       183 non-null    float64
 5   Weight       189 non-null    float64
 6   Transfer     188 non-null    object 
 7   Test_Number  200 non-null    int64  
 8   Test_Date    200 non-null    object 
 9   Time_Record  200 non-null    object 
dtypes: float64(2), int64(1), object(7)
memory usage: 15.8+ KB


Height      Weight  Test_Number
count  183.000000  189.000000   200.000000
mean   163.218033   55.015873     1.645000
std      8.608879   12.824294     0.722207
min    145.400000   34.000000     1.000000
25%    157.150000   46.000000     1.000000
50%    161.900000   51.000000     1.500000
75%    167.500000   65.000000     2.000000
max    193.900000   89.000000     3.000000

In [2]:
# 特征统计函数
df_demo = df[['Height', 'Weight']]
df_demo.mean()
df_demo.max()
# 分位数 quantile()  非缺失值个数 count() 最大值索引 idxmax()
df_demo.quantile(0.75)
df_demo.idxmax()

df_demo["BMI"] = df_demo['Weight'] / (df_demo['Height'] ** 2)
df.loc[df_demo['BMI'].idxmax(), 'Name']

C:\Users\Administrator\AppData\Local\Temp\ipykernel_20664\3729687490.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_demo["BMI"]=df_demo['Weight']/(df_demo['Height']**2)


'Chengpeng Zhou'

In [7]:
# 频次函数
df['School'].unique()
df['School'].nunique()
df['School'].value_counts(normalize=True)
df_demo = df[['Gender', 'Transfer', 'Name']]
df_demo.drop_duplicates(['Gender', 'Transfer'], keep='last')
df_demo.drop_duplicates(['Name', 'Gender'], keep=False).head()


Gender Transfer            Name
0  Female        N    Gaopeng Yang
1    Male        N  Changqiang You
2    Male        N         Mei Sun
4    Male        N     Gaojuan You
5  Female        N     Xiaoli Qian

In [16]:
# 替换函数
# 映射替换
df['Gender'].replace({'Female': 0, 'Male': 1}).head()
s = pd.Series(['a', 1, 'b', 2, 1, 1, 'a'])
s.replace([1, 2], method='ffill')
# 逻辑替换
s = pd.Series([-1, 1.2345, 100, -50])
s.where(s < 0, 'hahaha')
s.mask(s < 0, '2333')
# 数值替换
s.round(2)
s.clip(0, 10)
s.clip(0, 10).replace({0: "t0", 10: "t1"})


0        t0
1    1.2345
2        t1
3        t0
dtype: object

In [42]:
# 排序函数
df_demo = df[['Grade', 'Name', 'Height', 'Weight']].set_index(['Grade', 'Name'])
df_demo.sort_values('Height', ascending=False).head()
df_demo.sort_values(['Weight', 'Height'], ascending=[True, False]).head()
df_demo.sort_index(level=['Grade', 'Name'], ascending=[True, False]).head()

s = pd.Series(list("abceeedddd"))
s.rank(ascending=True, pct=False, method='dense')

0    1.0
1    2.0
2    3.0
3    5.0
4    5.0
5    5.0
6    4.0
7    4.0
8    4.0
9    4.0
dtype: float64

In [43]:
# apply函数
df_demo = df[['Height', 'Weight']]


def my_mean(x: pd.Series):
    return x.mean()


df_demo.apply(my_mean)


Height    163.218033
Weight     55.015873
dtype: float64

In [49]:
%timeit -n 100 -r 7 df_demo.apply( lambda x:x.mean(), axis=1)

16 ms ± 612 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
%timeit -n 100 -r 7 df_demo.mean()

265 µs ± 6.82 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 2.4 窗口函数

In [66]:
# 滑动窗口函数 rolling()
s = pd.Series(range(1, 6))
roller = s.rolling(window=3, min_periods=3)
roller.mean()
roller.sum()
# 类滑动窗口函数
# shift() 向前查询第几个元素
# diff() 向前第几个元素作差
# pct_change() 向前第几个元素的增长率
s.shift(2)
s.diff(2)
s.pct_change(-2)

roller.apply(lambda x: list(x)[0])
roller.apply(lambda x: list(x)[-1] - list(x)[0])
roller.apply(lambda x: list(x)[-1] / list(x)[0] - 1)


0         NaN
1         NaN
2    2.000000
3    1.000000
4    0.666667
dtype: float64

In [71]:
s = pd.Series([1, 2, 3])
roller = s[::-1].rolling(window=2)
roller.sum()[::-1]

0    3.0
1    5.0
2    NaN
dtype: float64

In [75]:
# 扩张窗口函数 expanding()
s = pd.Series([1, 3, 6, 10])
expander = s.expanding()
print(expander, type(expander))
expander.mean()


Expanding [min_periods=1,axis=0,method=single] <class 'pandas.core.window.expanding.Expanding'>


0    1.000000
1    2.000000
2    3.333333
3    5.000000
dtype: float64

In [79]:
s.cumsum()
s.cumprod()
expander.apply(lambda x: x.sum())
expander.apply(lambda x: x.prod())


0      1.0
1      3.0
2     18.0
3    180.0
dtype: float64

## 2.5 习题

In [139]:
# 整理某服装店的商品情况
df = pd.read_csv("./src/ch2/clothing_store.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   type_1      10000 non-null  object
 1   type_2      10000 non-null  object
 2   buy_price   10000 non-null  int64 
 3   sale_price  10000 non-null  int64 
 4   product_id  10000 non-null  object
dtypes: int64(2), object(3)
memory usage: 390.8+ KB


type_1 type_2  buy_price  sale_price product_id
0     裤子    游泳裤        145         154    S007721
1     鞋子     凉鞋         98         101    S007156
2     鞋子     拖鞋        122         149    S002286
3     鞋子     拖鞋         55          74    S009119
4     鞋子     凉鞋         79         112    S004373

In [140]:
df['profit'] = df['sale_price'] - df['buy_price']
df['profit'].mean()

24.3481

In [141]:
pattern = "商品一类级别为{}，二类级别为{}，进价和售价分别为{:d}和{:d}"
res: pd.Series = df.apply(lambda x: pattern.format(*x.values), axis=1)
res.index = df['product_id']
res.name = 'value'
res

product_id
S007721    商品一类级别为裤子，二类级别为游泳裤，进价和售价分别为145和154
S007156      商品一类级别为鞋子，二类级别为凉鞋，进价和售价分别为98和101
S002286     商品一类级别为鞋子，二类级别为拖鞋，进价和售价分别为122和149
S009119       商品一类级别为鞋子，二类级别为拖鞋，进价和售价分别为55和74
S004373      商品一类级别为鞋子，二类级别为凉鞋，进价和售价分别为79和112
                          ...                
S004636     商品一类级别为鞋子，二类级别为拖鞋，进价和售价分别为123和124
S001560     商品一类级别为鞋子，二类级别为拖鞋，进价和售价分别为106和113
S001280       商品一类级别为上衣，二类级别为T恤，进价和售价分别为68和75
S001207     商品一类级别为裤子，二类级别为长裤，进价和售价分别为113和139
S002475     商品一类级别为裤子，二类级别为中裤，进价和售价分别为122和138
Name: value, Length: 10000, dtype: object

In [142]:
df_demo = df[['type_1', 'type_2', 'product_id']].set_index("product_id")
res = df_demo.drop_duplicates(keep='first')
res.tail(1)


type_1 type_2
product_id              
S008754        裤子     拖鞋

In [145]:
df_demo = df.copy()
df_temp = df_demo.sort_values(["type_2", "profit"], ascending=[True, False])
df_temp_2 = df_temp.drop_duplicates("type_2", keep="first")
df_temp_2[['type_2', 'product_id']]


type_2 product_id
1405     T恤    S009881
162      中裤    S005119
820     冲锋衣    S009181
664      凉鞋    S001114
858      拖鞋    S002385
492     游泳裤    S009267
515     羽绒服    S003205
1073     跑鞋    S005340
1824     长裤    S005169

In [146]:
# 汇总某课程的学生总评分数
data = pd.read_csv("./src/ch2/student_grade.csv")
data.head()

Student_ID  Mid_Term_Grade  Final_Grade  Question_Answering_Times  \
0       S001            84.0         69.0                         0   
1       S002            81.0         83.0                         4   
2       S003            83.0         64.0                         1   
3       S004            66.0         89.0                         4   
4       S005            95.0         45.0                         4   

   Absence_Times  
0              0  
1              0  
2             10  
3              0  
4              0

In [150]:
data.sort_values(['Absence_Times', 'Question_Answering_Times'], ascending=[True, False]).head(1)

Student_ID  Mid_Term_Grade  Final_Grade  Question_Answering_Times  \
33       S034            67.0         92.0                        30   

    Absence_Times  
33              0

In [170]:
df_data = data.copy()
df_data['Question_Answering_Times'].clip(0, 10, inplace=True)
df_data['Summary'] = 0.4 * df_data['Mid_Term_Grade'] + 0.6 * df_data['Final_Grade'] + df_data[
    'Question_Answering_Times'] - 5 * df_data['Absence_Times']
df_data['Summary'].mask(df_data['Absence_Times'] > 5, 0, inplace=True)
df_data['Summary'].clip(0, 100, inplace=True)
df_data

Student_ID  Mid_Term_Grade  Final_Grade  Question_Answering_Times  \
0         S001            84.0         69.0                         0   
1         S002            81.0         83.0                         4   
2         S003            83.0         64.0                         1   
3         S004            66.0         89.0                         4   
4         S005            95.0         45.0                         4   
..         ...             ...          ...                       ...   
195       S196            84.0         67.0                         1   
196       S197            77.0         78.0                         0   
197       S198            71.0         63.0                         1   
198       S199            78.0         85.0                         0   
199       S200            83.0         75.0                         0   

     Absence_Times  Summary  
0                0     75.0  
1                0     86.2  
2               10      0.0  
3                0     83.8  
4                0     69.0  
..             ...      ...  
195              0     74.8  
196              2     67.6  
197              2     57.2  
198              0     82.2  
199              0     78.2  

[200 rows x 6 columns]

In [177]:
def to_level(x):
    x = x // 10
    if x in range(6, 8):
        res = '及格'
    elif x in range(8, 9):
        res = '良好'
    elif x in range(0, 6):
        res = '不及格'
    else:
        res = '优秀'
    return res


df_data['level'] = df_data['Summary'].apply(to_level)
df_data
df_data['level'].value_counts(normalize=True)

level
及格     0.50
良好     0.32
优秀     0.10
不及格    0.08
Name: proportion, dtype: float64

# 第三章 索引

## 3.1 单级索引

In [1]:
import pandas as pd

df = pd.read_csv("./src/learn_pandas.csv")
df.head()


School      Grade            Name  Gender  Height  Weight Transfer  \
0      A   Freshman    Gaopeng Yang  Female   158.9    46.0        N   
1      B   Freshman  Changqiang You    Male   166.5    70.0        N   
2      A     Senior         Mei Sun    Male   188.9    89.0        N   
3      C  Sophomore    Xiaojuan Sun  Female     NaN    41.0        N   
4      C  Sophomore     Gaojuan You    Male   174.0    74.0        N   

   Test_Number  Test_Date Time_Record  
0            1  2019/10/5     0:04:34  
1            1   2019/9/4     0:04:20  
2            2  2019/9/12     0:05:22  
3            2   2020/1/3     0:04:08  
4            2  2019/11/6     0:05:22

In [14]:
df_demo = df.set_index(["Name"]).copy()
df_demo.loc[((df_demo["School"] == "A") | (df_demo["School"] == "B" ))& (df_demo["Grade"] == "Freshman") & (df_demo["Gender"] == "Female")]


School     Grade  Gender  Height  Weight Transfer  Test_Number  \
Name                                                                           
Gaopeng Yang       A  Freshman  Female   158.9    46.0        N            1   
Qiang Chu          A  Freshman  Female   162.5    52.0        N            1   
Gaopeng Shi        B  Freshman  Female   162.9    48.0        N            1   
Quan Chu           B  Freshman  Female   154.7    43.0        N            1   
Changquan Chu      B  Freshman  Female   159.6    45.0        N            2   
Xiaopeng Han       B  Freshman  Female   164.1    53.0        N            1   
Changmei Feng      B  Freshman  Female   163.8    56.0        N            3   
Xiaopeng Zhao      A  Freshman  Female   161.0    53.0        N            3   
Peng Zhang         A  Freshman  Female   163.1     NaN        N            3   
Xiaoquan Sun       A  Freshman  Female   154.6    40.0        N            3   
Qiang Zhang        B  Freshman  Female   152.7    43.0        N            1   
Chunmei Shi        A  Freshman  Female   164.9    52.0        N            1   
Xiaomei Yang       A  Freshman  Female   159.3    49.0        N            1   
Xiaofeng Qian      A  Freshman  Female   158.5    49.0        N            1   
Chunmei Wang       B  Freshman  Female   151.2    43.0        N            2   

                Test_Date Time_Record  
Name                                   
Gaopeng Yang    2019/10/5     0:04:34  
Qiang Chu      2019/12/12     0:03:53  
Gaopeng Shi     2019/9/12     0:04:58  
Quan Chu       2019/11/28     0:04:47  
Changquan Chu   2019/12/9     0:04:18  
Xiaopeng Han   2019/12/18     0:05:20  
Changmei Feng   2019/11/8     0:04:41  
Xiaopeng Zhao   2019/9/25     0:05:13  
Peng Zhang      2019/9/23     0:04:31  
Xiaoquan Sun   2019/11/12     0:04:05  
Qiang Zhang    2019/11/30     0:05:27  
Chunmei Shi      2019/9/8     0:03:33  
Xiaomei Yang    2019/9/17     0:04:22  
Xiaofeng Qian  2019/10/19     0:05:26  
Chunmei Wang   2019/12/10     0:04:24

In [16]:
df_demo.query('(School in ["A","B"]) & (Grade == "Freshman") & (Gender == "Female")')

query_list=["Junior","Senior"]
df.query('Grade == @query_list').head()

School   Grade           Name  Gender  Height  Weight Transfer  \
2       A  Senior        Mei Sun    Male   188.9    89.0        N   
7       D  Junior  Gaoqiang Qian  Female   161.9    50.0        N   
9       B  Junior        Juan Xu  Female   164.8     NaN        N   
11      D  Junior    Xiaoquan Lv  Female   153.2    43.0        N   
12      A  Senior       Peng You  Female     NaN    48.0      NaN   

    Test_Number   Test_Date Time_Record  
2             2   2019/9/12     0:05:22  
7             1    2019/9/3     0:03:45  
9             3   2019/10/5     0:04:05  
11            2   2019/9/16     0:04:49  
12            2  2019/10/20     0:04:10

In [21]:
df_set_1=pd.DataFrame([[0,1],[1,2],[3,4]],index=pd.Index(['a','b','a'],name='id1'))
df_set_2=pd.DataFrame([[4,5],[2,6],[7,1]],index=pd.Index(['b','b','c'],name='id2'))
id1=df_set_1.index.unique()
id2=df_set_2.index.unique()
id1.intersection(id2)
id1.union(id2)
id1.difference(id2)
id1.symmetric_difference(id2)

Index(['a', 'c'], dtype='object')

## 3.2 多级索引

In [36]:
multi_index=pd.MultiIndex.from_product([list("ABCD"),[2,1,3]],sortorder=0)
multi_index.get_level_values(0)

Index(['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'D', 'D', 'D'], dtype='object')

## 3.3 常见索引方法